### ISSUE TITLE
Chapter 3 : Ansible Playbooks, Advanced Topics - register and when

### ISSUE THREAD

**Issue by srufle** [spurin/masteringansible#1]
At 11:55 there seems to be an editing glitch. The video talks about the changing the CentOS and Ubuntu values to 6 and 15, then you discuss Jinja turning things into an int for a second time. I suspect that you did multiple takes and someone made a mistake when it was edited together. Enjoying the videos

PS: This same thing happened in an earlier video, but I do not know which.

**Comment by spurin** [comment]
Thanks Stephen,

I very much appreciate your feedback.  I will review the video and send revisions through to Packt to resolve this.  Will keep the issue open until this is resolved.

Kind Regards


James Spurin

**Comment by spurin** [comment]
Requires removal/editing of 07:36 to 10:20

**Comment by spurin** [comment]
There was a recent update by Packt and I believe this has been resolved, will be recreating all videos for the next edition so closing for now.  Thanks @srufle
