### ISSUE TITLE
suggestion: install docker-py with pip module in playbook

### ISSUE THREAD

**Issue by minnjm** [spurin/masteringansible#3]
Following pull request is created for merge.

https://github.com/spurin/masteringansible/pull/2

**Comment by spurin** [comment]
Thanks @minnjm,

Great suggestion, will use this when we do our next update to the course.  Keeping the issue open for now.

**Comment by spurin** [comment]
I've changed Docker in the lab exercise to Docker in Docker, which resolves this :-)
