### ISSUE TITLE
Microsoft Azure and Ansible

### ISSUE THREAD

**Issue by cpatte7372** [spurin/masteringansible#4]
Hello James,

I have given rave reviews and 5 stars on your Mastering Ansible course in Udemy. 

You have section on AWS and Ansible. However, I'm an Microsoft Azure person and I was wondering if you have created any videos on Azure and Ansible? If not, could you recommend any course on Azure and Ansible?

Thanks

Carlton

**Comment by spurin** [comment]
Hi Carlton @cpatte7372,

Thanks so much for the reviews, I'm very grateful and am glad that you liked the course.  When I do revisions in the future, I'll definitely consider Azure.  If you found any helpful resources with regards to Azure, please share them here.

- James
