### ISSUE TITLE
issue with playing nginx_playbook.yml

### ISSUE THREAD

**Issue by rajburnwal07** [spurin/masteringansible#6]
![nginx_installation](https://user-images.githubusercontent.com/14872406/44268142-35e2b980-a24e-11e8-8123-46a1a715d3e7.JPG)

Hello sir , I have purchased your "Mastering ansible "  udemy course. I am facing problem with installing nginx server using nginx_playbook.yml file.  I have attached screenshot of problem. kindly resolve it.

**Comment by spurin** [comment]
Hi @rajkrburnwal,

Thanks for getting in touch.  I noticed that the IP's are different from those I provided in the vm lab so I'm guessing that you're using your own environment for this.  Would you mind elaborating on the setup that you're using please.

Possibly, there is a variation on the nginx server version/configuration, so the templates being applied may not be working as expected.  A 500 Internal Server Error suggests this is.

If you can share details about your setup, we can investigate further.

Thanks


James

**Comment by rajburnwal07** [comment]
actually problem is that  I don't have node machine separately.  my local
vm is control and node machine . Is there any problem with that?

**Comment by rajburnwal07** [comment]
and problem is coming at handler part but ping is successful and also
netstat -tulpn is showing that at 80 port nginx master is running..

**Comment by spurin** [comment]
@rajkrburnwal following up on this, the lab in this case, was reliant on the VM's supplied with the lab and the configuration for nginx that was available at the time.  I'm guessing, the variance in your setup resulted in a playbook execution that didnt tally up with what was expected.  It could be a good exercise to fix the playbook template if you desire.  The quick fix however, is to just use the lab vm's.

Closing this issue for now, thanks for your feedback above! 👍

**Comment by spurin** [comment]
Re-opening this, it should be an enhancement to the course in terms of guidance, when using your own control host there may be differences encountered

**Comment by spurin** [comment]
@rajkrburnwal  I've referenced this issue here https://masteringansible.com/2019/03/14/Using-your-own-control-host-with-the-lab/ and have credited you for the support, considering this closed.  Thanks
