### ISSUE TITLE
Vagrant to spin up machines?

### ISSUE THREAD

**Issue by Boeller666** [spurin/masteringansible#7]
Hi,

will it be possible to provide a Vagrantfile to spin up and down the whole infrastructure without downloading the VirtualBox-Zips?

Would be nice, as I also have problems with these machines (Ubuntu-c e.g. don't want to update itself)

**Comment by spurin** [comment]
Hi @Boeller666 

Excellent suggestion.  I will work on this as an enhancement.  If anyone wants to contribute I would also welcome contributions here.

Would you flag the update issues for me that you're seeing as a separate issue, would also like to get to the bottom of this and if necessary, push an update for the VM's.

Many Thanks


James

**Comment by Boeller666** [comment]
My update issue could be solved by disabling ipv6... seems to be an issue with my machine or network configuration.

thx anyway,
René

**Comment by spurin** [comment]
Hi @Boeller666 

I have pushed up new versions of the Virtual Machines.  I think that the motd that comes with the stock Ubuntu hasn't helped here, as really, there shouldn't be a need to update the VM for the purposes of the course (unless the user, implicitly wants to do so).  Could you when you have a moment, please try the new VM's, details are here -

https://masteringansible.com/2019/03/14/Update-Virtual-Machine-Images/
https://masteringansible.com/2019/03/10/Virtual-Machine-Download/

If you do get a networking issue with ipv6 again, if you could shed some light, I'll put more context on the main page.  Closing the issue for now.

Many Thanks

James
