### ISSUE TITLE
assumed user name in host of packt

### ISSUE THREAD

**Issue by queglay** [spurin/masteringansible#9]
when setting up this tutorial in your os, its assumed that the current user name is packt.  The problem is, most of us wont go to the trouble of making a new user to do the tutorial, and then you'll find that if you try to ssh in around here it wont work, because you wont be sshing into the other hosts as the user packt with ansible.
https://www.udemy.com/mastering-ansible-x/learn/v4/t/lecture/9300276?start=834

the solution is the ansible hosts file needs to use strings like this
[all]
centos1 ansible_user=packt

So that ssh will function correctly.

**Comment by spurin** [comment]
Thanks for sharing your experience.  If you're using the virtual machines that are provided as the control host then you don't have this issue but yes, if instead you choose to have your own control host, this should be part of the setup process.  I'll consider adding this as a mention on the next coure update.

**Comment by spurin** [comment]
@queglay I've referenced this issue here https://masteringansible.com/2019/03/14/Using-your-own-control-host-with-the-lab/ and have credited you for the support, considering this closed.  Thanks
